config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'apply', to: 'experts#new'
  #post 'apply', to: 'experts#create'
  resources :experts do
    resources :offered_courses
  end

  resources :offered_courses, only: [:index, :show, :create, :update] do
    resource :expert, only: [:show]
  end

  get 'signup', to: 'newbies#new'
  #post 'signup', to: 'newbies#create'
  resources :newbies, except: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expert.rb
class Expert < ApplicationRecord

  has_many :courses
  has_many :newbies, through: :courses
  has_secure_password

  def full_name
    self.first_name + " " + self.last_name
  end

end

app/models/newbie.rb
class Newbie < ApplicationRecord

  has_many :courses
  has_many :experts, through: :courses
  has_secure_password

  def full_name
    self.first_name + " " + self.last_name
  end

end

app/models/offered_course.rb
class OfferedCourse < ApplicationRecord

  belongs_to :expert

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_expert
    @current_expert ||= Expert.find(session[:user_id]) if session[:user_id]
  end

  def current_newbie
    @current_newbie ||= Newbie.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_expert || !!current_newbie
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must log in first."
      redirect_to login_path
    end
  end

end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController

  before_action :set_expert, only:[:show, :edit, :update, :destroy]
  

  def index
    @experts = Expert.all
  end

  def show
  end

  def new
    @expert = Expert.new
  end

  def create
    @expert = Expert.new(expert_params)
    if @expert.save
      session[:user_id] = @expert.id
      # flash[:notice] = 'Congratulations! You have been accepted as an EdBest Expert.'
      redirect_to @expert
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @expert.update(expert_params)
      # flash[:notice] = 'Your profile has been updated.'
      redirect_to @expert
    else
      render 'edit'
    end
  end

  def destroy
    @expert.destroy
    session[:user_id] = nil if @expert == current_expert
    #flash[:notice] = 'Account, courses, and all related data have been destroyed'
    redirect_to root_path
  end

  private

  def course
    if params[:offered_course_id]
      OfferedCourse.find(params[:offered_course_id])
    end
  end

  def set_expert
    @expert = Expert.find(params[:id] || course.expert.id)
  end

  def expert_params
    params.require(:expert).permit(:first_name, :last_name, :email, :password, :bio)
  end

end

app/controllers/newbies_controller.rb
class NewbiesController < ApplicationController

  before_action :set_newbie, only:[:show, :edit, :update, :destroy]


  def index
    @newbies = Newbie.all
  end

  def show
  end

  def new
    @newbie = Newbie.new
  end

  def create
    # byebug
    @newbie = Newbie.new(newbie_params)
    if @newbie.save
      session[:user_id] = @newbie.id
      # flash[:notice] = "Welcome to EdBest, #{@newbie.first_name}!"
      redirect_to newby_path(@newbie)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @newbie.update(newbie_params)
      # flash[:notice] = 'Your profile has been updated.'
      redirect_to @newbie
    else
      render 'edit'
    end
  end

  def destroy
    @newbie.destroy
    session[:user_id] = nil if @newbie == current_newbie
    # flash[:notice] = 'Account, courses, and all related data have been destroyed'
    redirect_to root_path
  end

  private

  def set_newbie
    @newbie = Newbie.find(params[:id])
  end

  def newbie_params
    params.require(:newbie).permit(:first_name, :last_name, :email, :password)
  end

end

app/controllers/offered_courses_controller.rb
class OfferedCoursesController < ApplicationController

  before_action :set_course, only:[:show, :edit, :update, :destroy]

  def new
    @o_course = OfferedCourse.new
  end

  def create
    @o_course = OfferedCourse.new(course_params)
    @o_course.expert = current_expert
    if @o_course.save
      #flash[:notice] = 'Course added successfully.'
      redirect_to @o_course.expert
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @o_course.update(course_params)
      #flash[:notice] = 'Course presentation was updated successfully.'
      redirect_to expert_offered_courses_path(@o_course.expert)
    else
      render 'edit'
    end
  end

  def index
    @o_courses = OfferedCourse.all
  end

  def show
  end

  def destroy
    @o_course.destroy
    redirect_to expert_offered_courses_path(@o_course.expert)
  end

  private

  def set_course
    @o_course = OfferedCourse.find(params[:id])
  end

  def course_params
    params.require(:offered_course).permit(:name, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if params[:session][:expert] == "1"
      user = Expert.find_by(email: params[:session][:email].downcase)
    else
      user = Newbie.find_by(email: params[:session][:email].downcase)
    end
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.first_name}!"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Come back soon!"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experts_helper.rb
module ExpertsHelper
end

app/helpers/newbies_helper.rb
module NewbiesHelper
end

app/helpers/offered_courses_helper.rb
module OfferedCoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/experts/_form.html.erb
<%= form_with model: @expert, class: "" do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :bio %>
  <%= f.text_area :bio, rows: 3 %>
  <%= f.submit "Submit" %>
<% end %>

app/views/experts/edit.html.erb
<h1>Edit Your Profile</h1>
<%= render 'form' %>

app/views/experts/index.html.erb
<h1>Check Out Our Awesome Experts!</h1>
<% @experts.each do |expert| %>
  <h2><%= link_to expert.full_name, expert_path(expert) %></h2>
  <p><%= expert.bio %></p>
<% end %>

app/views/experts/new.html.erb
<h1>Apply To Be An EdBest Expert!</h1>
<%= render 'form' %>

app/views/experts/show.html.erb
<h1><%= @expert.full_name %></h1>
<p><%= @expert.bio %></p>
<h3><%= link_to "See #{@expert.first_name}'s Courses", expert_offered_courses_path(@expert) %></h3>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Log In', login_path %>
<%= link_to 'Log Out', logout_path, method: :delete %>
<%= link_to 'Sign Up', signup_path %>
<%= link_to 'Apply', apply_path %>
<%= link_to 'Courses', offered_courses_path %>
<%= link_to 'Experts', experts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EdBest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/newbies/_form.html.erb
<%= form_with model: @newbie, class: "" do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Submit" %>
<% end %>

app/views/newbies/edit.html.erb
<h1>Edit Your Profile</h1>
<%= render 'form' %>

app/views/newbies/index.html.erb
<h1>Newbies</h1>
<% @newbies.each do |newbie| %>
  <h2><%= link_to newbie.full_name newbie_path(newbie) %></h2>
<% end %>

app/views/newbies/new.html.erb
<h1>Sign Up To Start Learning!</h1>
<%= render 'form' %>

app/views/newbies/show.html.erb
<h1><%= @newbie.full_name %></h1>
<h3><%= @newbie.first_name %>'s Courses</h3>

app/views/offered_courses/_form.html.erb
<%= form_with model: @o_course, class: "" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit "Submit" %>
<% end %>

app/views/offered_courses/edit.html.erb
<h1>Edit Your Course Presentation</h1>
<%= render 'form' %>

app/views/offered_courses/index.html.erb
<h1>Check Out Our Awesome Courses!</h1>
<% @o_courses.each do |course| %>
  <h2><%= link_to course.name, course %></h2>
<% end %>

app/views/offered_courses/new.html.erb
<h1>Add a New Course</h1>
<%= render 'form' %>

app/views/offered_courses/show.html.erb
<h1><%= @o_course.name %></h1>
<h3><%= link_to @o_course.expert.full_name, [@o_course, @o_course.expert] %></h3>
<p><%= @o_course.description %></p>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>